#include "atomic.h"

#ifdef ATOMIC_EVAL

// default ATOMIC_MOBILITY_MULTIPLIER / ATOMIC_MOBILITY_DIVISOR = 1

int ATOMIC_MOBILITY_MULTIPLIER = 8;

int ATOMIC_MOBILITY_DIVISOR    = 3;

// tested with 10 / 3

// default ATOMIC_GAME_PHASE_MULTIPLIER / ATOMIC_GAME_PHASE_DIVISOR = 1

// tested with 1

int ATOMIC_GAME_PHASE_MULTIPLIER = 2;

int ATOMIC_GAME_PHASE_DIVISOR = 3;

// default ATOMIC_PASSED_PAWN_MULTIPLIER / ATOMIC_PASSED_PAWN_DIVISOR = 5

// tested with 3

int ATOMIC_PASSED_PAWN_MULTIPLIER = 5;

int ATOMIC_PASSED_PAWN_DIVISOR = 2;
		
#endif