#include "atomic.h"

#ifdef ATOMIC_EVAL

// default ATOMIC_MOBILITY_MULTIPLIER / ATOMIC_MOBILITY_DIVISOR = 1

int ATOMIC_MOBILITY_MULTIPLIER = 10;

int ATOMIC_MOBILITY_DIVISOR    = 3;

// default ATOMIC_GAME_PHASE_FACTOR = 1

int ATOMIC_GAME_PHASE_FACTOR   = 1;

// default ATOMIC_PASSED_PAWN_FACTOR = 5

int ATOMIC_PASSED_PAWN_FACTOR  = 3;
		
#endif